[versions]
gradle-android = "8.0.2"
gradle-dependency-handler-extensions = "1.1.0"

kotlin-core = "1.8.21"
kotlin-detekt = "1.23.0"
kotlin-ktlint-gradle = "11.3.2"
kotlin-ktlint-source = "0.48.2"

kotlinx-coroutine = "1.7.1"

android-material = "1.9.0"

androidx-core = "1.8.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.7.0-beta01"

test-kotest = "5.6.2"
test-junit-core = "4.13.2"
test-junit-engine = "5.9.3"
test-roborazzi = "1.3.0-alpha-1"
test-robolectric = "4.10.3"

hilt = "2.45"
hilt-navigation = "1.0.0"

[plugins]
gradle-dependency-handler-extensions = { id = "land.sungbin.dependency.handler.extensions", version.ref = "gradle-dependency-handler-extensions" }

android-library = { id = "com.android.library", version.ref = "gradle-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-core" }

navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-core" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
kotlin-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "kotlin-detekt" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

test-roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "test-roborazzi" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }

# This isn't strictly used but allows Renovate to see us using the ktlint artifact
kotlin-ktlint = { module = "com.pinterest:ktlint", version.ref = "kotlin-ktlint-source" }

android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "kotlin-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }

androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hilt-navigation" }

kotlinx-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutine"}

test-kotest-framework = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "test-kotest" }
test-kotest-assertion = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" } # testRuntimeOnly
test-roborazzi-core = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "test-roborazzi" }
test-roborazzi-rule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "test-roborazzi" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }

detekt-plugin-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "kotlin-detekt" }

[bundles]
test-roborazzi = ["test-roborazzi-core", "test-roborazzi-rule"]
androidx-lifecycle = ["androidx-lifecycle-runtime", "androidx-lifecycle-viewmodel", "androidx-lifecycle-savedstate"]
androidx-navigation = ["androidx-navigation-ui", "androidx-navigation-fragment"]