[versions]
gradle-android = "8.0.2"
gradle-dependency-handler-extensions = "1.1.0"

kotlin-core = "1.8.21"
kotlin-detekt = "1.23.0"
kotlin-ktlint-gradle = "11.3.2"
kotlin-ktlint-source = "0.48.2"

android-material = "1.9.0"

androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"

test-junit-core = "4.13.2"
test-junit-engine = "5.9.3"
test-roborazzi = "1.3.0-alpha-1"
test-robolectric = "4.10.3"

[plugins]
gradle-dependency-handler-extensions = { id = "land.sungbin.dependency.handler.extensions", version.ref = "gradle-dependency-handler-extensions" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
kotlin-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "kotlin-detekt" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

test-roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "test-roborazzi" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }

# This isn't strictly used but allows Renovate to see us using the ktlint artifact
kotlin-ktlint = { module = "com.pinterest:ktlint", version.ref = "kotlin-ktlint-source" }

android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }

test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" } # testRuntimeOnly
test-roborazzi-core = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "test-roborazzi" }
test-roborazzi-rule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "test-roborazzi" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }

detekt-plugin-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "kotlin-detekt" }

[bundles]
test-roborazzi = ["test-roborazzi-core", "test-roborazzi-rule"]
